[package]
name = "waco"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-web = "4.6.0"
async-channel = "2.3.1"
async-std = "1.12.0"
axum = "0.7.5"
chrono = "0.4.38"
env_logger = "0.11.3"
futures-util = "0.3.30"
http = "1.1.0"
http-body-util = "0.1.1"
hyper = "1.3.1"
hyper-util = "0.1.5"
lazy_static = "1.4.0"
log = "0.4.21"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.4"
rustls = "0.23.8"
rustls-pemfile = "2.1.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = "1.37.0"
tokio-rustls =  {version="0.26.0" , default-features = false }
tower-service = "0.3.2"
tracing = "0.1.40"



[dev-dependencies]
hyper-util = { version = "0.1.5", default-features = false, features = ["server-auto"] }
rustls = { version = "0.23.8", default-features = false, features = ["tls12"] }
rustls-pemfile = "2.1.2"
tokio = { version = "1.37.0", features = ["io-std", "macros", "net", "rt-multi-thread"] }